# Generated by Django 5.2.6 on 2025-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quntity', models.IntegerField()),
                ('prize', models.IntegerField()),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
