# Generated by Django 5.2.8 on 2025-11-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_producttable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentable',
        ),
        migrations.AlterField(
            model_name='producttable',
            name='prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='quntity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
